name: Deploy to Firebase Hosting on Push
on:
  push:
    branches:
      - main # Or your main development branch
      # - develop # Uncomment if you want to trigger on pushes to develop
# permissions: # You likely don't need to change these
#   checks: write
#   contents: read
#   pull-requests: write
jobs:
  build_and_deploy: # Changed job name to be more descriptive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_V_CONNECTION_WEBPAGE }}
          projectId: v-connection-webpage
          entrypoint: ./
          publicDir: .next # Adjust if your build output is different