name: Deploy to Firebase Hosting on Push
on:
  push:
    branches:
      - main # Or your main development branch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build # Ensures static export to 'out'

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools@latest
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_V_CONNECTION_WEBPAGE }}" > /tmp/serviceAccount.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/serviceAccount.json"
          firebase deploy --project=${{ env.FIREBASE_PROJECT_ID }} --config firebase.json --only hosting
          rm /tmp/serviceAccount.json

        env:
          FIREBASE_PROJECT_ID: v-connection-webpage